### ISSUE TITLE
Error when run ./go-architect

### ISSUE THREAD

**Issue by lechuhuuha** [fdaines/go-architect#17]
Hi i had built the binary file 
here is my setup i'm using wsl in windows 10

```cmd
# Wails
Version         | v2.7.1
Package Manager | apt

# System
┌──────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                    |
| Version      | 22.04                                     |
| ID           | ubuntu                                    |
| Go Version   | go1.21.1                                  |
| Platform     | linux                                     |
| Architecture | amd64                                     |
| CPU          | Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz |
| GPU          | Unknown                                   |
| Memory       | 12GB                                      |
└──────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Installed | 24.0.5-0ubuntu1~22.04.1 |
| gcc        | build-essential       | Installed | 12.9ubuntu3             |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2        |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.42.3-0ubuntu0.22.04.1 |
| npm        | npm                   | Installed | 8.5.1~ds-1              |
| *nsis      | nsis                  | Installed | v3.08-2                 |
| pkg-config | pkg-config            | Installed | 0.29.2                  |
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
CGO_ENABLED=1 wails build -clean
Wails CLI v2.7.1


# Build Options

Platform(s)        | linux/amd64
Compiler           | /usr/local/go/bin/go
Skip Bindings      | false
Build Mode         | production
Devtools           | false
Frontend Directory | /root/go-architect/frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | false
Package            | true
Clean Bin Dir      | true
LDFlags            |
Tags               | []
Race Detector      | false
Warning: go.mod is using Wails '2.6.0' but the CLI is 'v2.7.1'. Consider updating your project's `go.mod` file.


# Building target: linux/amd64

  • Generating bindings: 2023/12/25 08:58:52 KnownStructs: comments.CommentsMetrics     coupling.DependencyCoupling    dependency.ModuleDependencyGraph dsm.DependencyStructureMatrix   git.VCSAnalysisInfo     gocyclo.GoCycloOutput   instability.PackageInstability  interfaces.InterfaceInfo        interfaces.InterfaceMetrics     loc.FileLOC     loc.PackageLOC loc.ProjectLOC   project.ProjectInfo     repository.RepositoryInfo       storage.HistoricalMetrics       storage.Metricsstorage.Project  storage.ProjectList     storage.SelectedProject types.PackageTypes      types.ProjectTypes
storage.Metrics

Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
  • Compiling application: Done.
  • Packaging application: Done.
Built '/root/go-architect/build/bin/go-architect' in 11.999s.
```

after run the binary file i get this error

```cmd
root@LAPTOP-0FF7JIML:~/go-architect# ls
LICENSE   README.md  app.go       backend  frontend      go.mod  main.go
Makefile  api.go     appdmg.json  build    go-architect  go.sum  wails.json
root@LAPTOP-0FF7JIML:~/go-architect# ./go-architect
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
libEGL warning: MESA-LOADER: failed to open vgem: /usr/lib/dri/vgem_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

signal 11 received but handler not on signal stack
mp.gsignal stack [0xc000008000 0xc000010000], mp.g0 stack [0x7ffdfe35b9e0 0x7ffdfeb5a9f0], sp=0xc0001ff358
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0xb6ed2a?, 0xc0000d5d00?})
        /usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc0001ff2b0 sp=0xc0001ff280 pc=0x440e9c
runtime.sigNotOnStack(0xb, 0xc0001ff330?, 0x1371ac0)
        /usr/local/go/src/runtime/signal_unix.go:1045 +0x145 fp=0xc0001ff2e8 sp=0xc0001ff2b0 pc=0x4578e5
runtime.adjustSignalStack(0xb, 0x1371ac0, 0xc0001ff380)
        /usr/local/go/src/runtime/signal_unix.go:592 +0x291 fp=0xc0001ff358 sp=0xc0001ff2e8 pc=0x456731
runtime.sigtrampgo(0xb, 0xc0001ff670, 0xc0001ff540)
        /usr/local/go/src/runtime/signal_unix.go:480 +0xd5 fp=0xc0001ff3d0 sp=0xc0001ff358 pc=0x456215
runtime.sigtramp()
        /usr/local/go/src/runtime/sys_linux_amd64.s:352 +0x46 fp=0xc0001ff420 sp=0xc0001ff3d0 pc=0x474ea6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x473341

goroutine 1 [running, locked to thread]:
        goroutine running on other thread; stack unavailable

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00006afa8 sp=0xc00006af88 pc=0x443d6e
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc00006afe0 sp=0xc00006afa8 pc=0x443bf3
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006afe8 sp=0xc00006afe0 pc=0x473341
created by runtime.init.6 in goroutine 1
        /usr/local/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00006b778 sp=0xc00006b758 pc=0x443d6e
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc00006b7c8 sp=0xc00006b778 pc=0x42fbd4
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc00006b7e0 sp=0xc00006b7c8 pc=0x424d65
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006b7e8 sp=0xc00006b7e0 pc=0x473341
created by runtime.gcenable in goroutine 1
        /usr/local/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0xeffc80?, 0x1?, 0x0?, 0xc0000071e0?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00006bf70 sp=0xc00006bf50 pc=0x443d6e
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1370fc0)
        /usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00006bfa0 sp=0xc00006bf70 pc=0x42d469
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc00006bfc8 sp=0xc00006bfa0 pc=0x42d9fc
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc00006bfe0 sp=0xc00006bfc8 pc=0x424d05
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x473341
created by runtime.gcenable in goroutine 1
        /usr/local/go/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0xb40a80?, 0x100444f01?, 0x0?, 0x0?, 0x44bf25?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00006a628 sp=0xc00006a608 pc=0x443d6e
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00006a7e0 sp=0xc00006a628 pc=0x423de7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006a7e8 sp=0xc00006a7e0 pc=0x473341
created by runtime.createfing in goroutine 1
        /usr/local/go/src/runtime/mfinal.go:163 +0x3d

goroutine 6 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00006c6e8 sp=0xc00006c6c8 pc=0x443d6e
runtime.chanrecv(0xc0001b29c0, 0xc00006c7a8, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc00006c760 sp=0xc00006c6e8 pc=0x4117ad
runtime.chanrecv2(0x0?, 0x0?)
        /usr/local/go/src/runtime/chan.go:447 +0x12 fp=0xc00006c788 sp=0xc00006c760 pc=0x4113d2
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startRequestProcessor(0xc0001b2f60)
        /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:494 +0x57 fp=0xc00006c7c8 sp=0xc00006c788 pc=0x9ef997
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func3()
        /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:179 +0x25 fp=0xc00006c7e0 sp=0xc00006c7c8 pc=0x9ed9c5
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x473341
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend in goroutine 1
        /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:179 +0x52f

goroutine 7 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00006cee0 sp=0xc00006cec0 pc=0x443d6e
runtime.chanrecv(0xc0001b2960, 0xc00006cfa8, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc00006cf58 sp=0xc00006cee0 pc=0x4117ad
runtime.chanrecv2(0x0?, 0x0?)
        /usr/local/go/src/runtime/chan.go:447 +0x12 fp=0xc00006cf80 sp=0xc00006cf58 pc=0x4113d2
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0x0?)
        /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:208 +0x57 fp=0xc00006cfc8 sp=0xc00006cf80 pc=0x9eda57
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func4()
        /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:182 +0x25 fp=0xc00006cfe0 sp=0xc00006cfc8 pc=0x9ed965
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x473341
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend in goroutine 1
        /root/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:182 +0x571
```

**Comment by lechuhuuha** [comment]
they fixed for ubuntu
