### ISSUE TITLE
I'm having issues like this:

### ISSUE THREAD

**Issue by qq1792569310** [fdaines/go-architect#22]
When compiling with the wails build or wails dev command, the console gives the following error:

  ERROR   
          panic: open \.goarchitect\goarchitect.log: The system cannot find the path specified.
          
          goroutine 1 [running]:
          main.checkForLoggingFile({0xc000034860, 0x1d})
                E:/_Project/GoCode/project/gui/wailsProject/go-architect/main.go:90 +0xdc
          main.resolveWailsOptions()
                E:/_Project/GoCode/project/gui/wailsProject/go-architect/main.go:43 +0x85
          main.main()
                E:/_Project/GoCode/project/gui/wailsProject/go-architect/main.go:34 +0xb8
         
          exit status 2

The same goes for using the make install command

**Comment by fdaines** [comment]
Could you please add the output from `wails doctor` command? This is important to gather some info from your system

**Comment by qq1792569310** [comment]
> Could you please add the output from `wails doctor` command? This is important to gather some info from your system

This is the information generated by the wails doctor command, but my Windows system version should be Windows11, which should not affect the running result......

```


          Wails Doctor



# Wails
Version | v2.7.1

# System
┌───────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Home China                                              |
| Version      | 2009 (Build: 22000)                                                |
| ID           | 21H2                                                               |
| Go Version   | go1.21.5                                                           |
| Platform     | windows                                                            |
| Architecture | amd64                                                              |
| CPU          | 12th Gen Intel(R) Core(TM) i7-12700H                               |
| GPU          | NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA) - Driver: 31.0.15.3141 |
| Memory       | 16GB                                                               |
└───────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version                 |
| WebView2   | N/A          | Installed | 119.0.2151.44           |
| Nodejs     | N/A          | Installed | 18.18.0                 |
| npm        | N/A          | Installed | Active code page: 65001 |
| *upx       | N/A          | Available |                         |
| *nsis      | N/A          | Available |                         |
└──────────────────── * - Optional Dependency ────────────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```
![QQ截图20231230150417](https://github.com/go-architect/go-architect/assets/80034716/d81bbbee-6ccd-445e-bb5e-dffca3e4ee6a)

**Comment by fdaines** [comment]
@qq1792569310 It seems to be an issue when trying to resolve logfile path. Could you please check if branch [22-homepath-issue-in-windows](https://github.com/go-architect/go-architect/tree/22-homepath-issue-in-windows) solves the issue?

```
git fetch
git checkout 22-homepath-issue-in-windows
```

**Comment by qq1792569310** [comment]
> @qq1792569310 It seems to be an issue when trying to resolve logfile path. Could you please check if branch [22-homepath-issue-in-windows](https://github.com/go-architect/go-architect/tree/22-homepath-issue-in-windows) solves the issue?
> 
> ```
> git fetch
> git checkout 22-homepath-issue-in-windows
> ```

I executed the method you provided, but it still hasn't been fixed, the console information seems to be looking for a file in my user directory, but I can't find it, I go to my file system, and I don't see the files and folders I need。

```
  • Generating bindings:   ERROR   
          panic: open C:\Users\cz\.goarchitect\goarchitect.log: The system cannot find the path specified.
         
          goroutine 1 [running]:
          main.checkForLoggingFile({0xc00002f590, 0x28})
                D:/_Project/wailsProject/go-architect/main.go:95 +0xdc
          main.resolveWailsOptions()
                D:/_Project/wailsProject/go-architect/main.go:48 +0xc5
          main.main()
                D:/_Project/wailsProject/go-architect/main.go:35 +0xb8
         
          exit status 2

  ERROR  
          panic: open C:\Users\cz\.goarchitect\goarchitect.log: The system cannot find the path specified.
         
          goroutine 1 [running]:
          main.checkForLoggingFile({0xc00002f590, 0x28})
                D:/_Project/wailsProject/go-architect/main.go:95 +0xdc
          main.resolveWailsOptions()
                D:/_Project/wailsProject/go-architect/main.go:48 +0xc5
          main.main()
                D:/_Project/wailsProject/go-architect/main.go:35 +0xb8
         
          exit status 2
```

**Comment by qq1792569310** [comment]
> @qq1792569310 It seems to be an issue when trying to resolve logfile path. Could you please check if branch [22-homepath-issue-in-windows](https://github.com/go-architect/go-architect/tree/22-homepath-issue-in-windows) solves the issue?
> 
> ```
> git fetch
> git checkout 22-homepath-issue-in-windows
> ```


I noticed that the project requires the following packages, I didn't install the other two except go, is that the cause of the bug?
```
Requirements
Go v1.19 (https://go.dev/doc/install)
GoCyclo (https://pkg.go.dev/github.com/fzipp/gocyclo) for Cyclomatic complexity metrics
GoCyclo （ https://pkg.go.dev/github.com/fzipp/gocyclo） 用于圈复杂度指标
GoCognit (https://pkg.go.dev/github.com/uudashr/gocognit) for Cognitive complexity metrics
```

**Comment by fdaines** [comment]
@qq1792569310, after a couple of days I detected that some functions (to retrieve environment variables) doesn't work well on Windows, so I changed them.
Can you please check if the new update on `22-homepath-issue-in-windows` branch solves the issue?
```
git checkout 22-homepath-issue-in-windows
git pull -r
```
